### ISSUE TITLE
Dataset access

### ISSUE THREAD

**Issue by etiennebeaulac** [stockeh/canine-embedded-ml#13]
Great project!

Is the dataset used to train the models publicly available somewhere? I can't seem to find it.

I am teaching AI to HS students and I would love to use this dataset as an example.

Thank you!

**Comment by gt732** [comment]
@stockeh This is a long shot but will also like to access the dataset to try the same project with my jetson nano. Thanks!!

**Comment by stockeh** [comment]
@gt732 thanks for the inquiry! Let me dig around and see if I have the data archived.

**Comment by gt732** [comment]
@stockeh , I wasn't expecting a reply and am extremely grateful for your response and the work detailed in your paper. Struggling with a pose estimation model I developed using DeepLabCut, I successfully trained it for my Boston Terrier puppy, extracting keypoints for pose estimation. 

However, determining if he was sitting by analyzing angles from keypoints led to many false positives. Your approach in the paper seems much more straightforward for accomplishing action determination via image classification. As a newcomer to ML and pursuing it as a hobby, I appreciate how the complexity has been simplified, making this technology accessible for people like me. 

If you could share the labeled dataset or the saved checkpoint .pb files, it would be incredible. This would allow me to experiment with transfer learning using pictures of my puppy.

**Comment by stockeh** [comment]
@gt732 I love that you're using this with your own pup! We had done the same with our model and found great success, albeit a well curated pose estimation dataset sounds promising. I don't have model checkpoints any longer, sadly, but models can be trained following [this notebook](https://github.com/stockeh/canine-embedded-ml/blob/main/notebooks/stock-machine-learning.ipynb). 

Our dataset is now available on HuggingFace: https://huggingface.co/datasets/stockeh/dog-pose-cv 

Happy classifying! 😄

**Comment by chloepar** [comment]
Just wanted to mention I will also be using this data for a school project - thanks so much for making it public!
